import { test } from "node:test";
import assert from "node:assert/strict";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { collectNearMisses, proposalsFrom } from "../scripts/detect-near-miss.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// Synthetic commits keep these tests independent of the checkout's real git state.
const COMMITS = [
  { an: "Mistral Bot", ae: "x@mistral.ai", cn: "Mistral Bot", ce: "x@mistral.ai", sha: "aaa111", body: "Add feature\n\nGenerated by Mistral large" },
  { an: "nateshpp", ae: "x@users.noreply.github.com", cn: "nateshpp", ce: "x@users.noreply.github.com", sha: "bbb222", body: "A clean commit body" },
];

test("collectNearMisses finds branch, identity, and attributed text near-misses", () => {
  const findings = collectNearMisses({ branch: "wip/claude-code", commits: COMMITS });
  const surfaces = new Set(findings.map((f) => f.surface));
  assert.ok(surfaces.has("branch"), "branch near-miss (claude-code) expected");
  assert.ok(surfaces.has("identity"), "identity near-miss (mistral) expected");
  assert.ok(surfaces.has("text"), "text near-miss (Generated by Mistral) expected");
});

test("collectNearMisses does not double-count committer when it equals author", () => {
  const findings = collectNearMisses({ branch: "main", commits: COMMITS });
  const identity = findings.filter((f) => f.surface === "identity");
  // Author and committer are the same identity, so only one identity finding.
  assert.equal(identity.length, 1);
});

test("collectNearMisses is clean when nothing is a near-miss", () => {
  const clean = [{ an: "nateshpp", ae: "x@users.noreply.github.com", cn: "nateshpp", ce: "x@users.noreply.github.com", sha: "ccc333", body: "Ordinary change" }];
  assert.deepEqual(collectNearMisses({ branch: "governance/attribution-near-miss", commits: clean }), []);
});

test("proposalsFrom collapses to one proposal per unique (tier, surface, token)", () => {
  const dupes = [
    { tier: 1, surface: "text", token: "mistral", where: "a:1" },
    { tier: 1, surface: "text", token: "mistral", where: "b:2" },
    { tier: 1, surface: "identity", token: "mistral", where: "a" },
  ];
  const proposals = proposalsFrom(dupes);
  assert.equal(proposals.length, 2);
  // The first occurrence is kept as evidence.
  assert.equal(proposals[0].where, "a:1");
});

test("the scanner CLI always exits 0 without --write (advisory, never blocks CI)", () => {
  const r = spawnSync("node", [join(root, "scripts/detect-near-miss.mjs")], { encoding: "utf8", timeout: 30000 });
  assert.strictEqual(r.status, 0, `expected exit 0 regardless of findings:\n${r.stdout}\n${r.stderr}`);
});
