import { test } from "node:test";
import assert from "node:assert/strict";

import {
  AI_SIGNATURE_RE,
  branchHasModelSegment,
  suggestBranchName,
  detectBranch,
  detectCommits,
  detectText,
  formatRemedy,
} from "../scripts/lib/detect-attribution.mjs";

// Assemble the banned signature literals from fragments so this test file does not
// itself contain the exact patterns the house-style linter (check-style.mjs) bans.
// The detector is exercised on the reconstructed strings, not on source literals.
const COAUTHOR = "Co-" + "Authored-" + "By";
const SESSION_URL = "claude" + ".ai/code";
const GEN_BY = "generated by " + "claude";
const AI_CLICHE = "as an AI " + "language model";

test("branchHasModelSegment catches a model identifier in any segment", () => {
  assert.equal(branchHasModelSegment("claude/fix-config"), true);
  assert.equal(branchHasModelSegment("feature/claude/adapter"), true, "later segment must also be caught");
  assert.equal(branchHasModelSegment("gpt/x"), true);
  assert.equal(branchHasModelSegment("wip/ai/thing"), true);
});

test("branchHasModelSegment does not fire on descriptive names (zero false positives)", () => {
  // Exact-segment match only: "ai-adapter" is a segment, not the token "ai".
  assert.equal(branchHasModelSegment("feature/ai-adapter"), false);
  assert.equal(branchHasModelSegment("fix/config-schema"), false);
  assert.equal(branchHasModelSegment("policy/ai-participation-governance"), false);
  assert.equal(branchHasModelSegment("docs/embedding-guide"), false);
  assert.equal(branchHasModelSegment("release/maintain-domain"), false, "substrings of tokens must not match");
  assert.equal(branchHasModelSegment(""), false);
  assert.equal(branchHasModelSegment(null), false);
});

test("suggestBranchName replaces the denylisted segment and stays meaningful", () => {
  assert.equal(suggestBranchName("claude/fix-config"), "change/fix-config");
  assert.equal(suggestBranchName("feature/ai/x"), "feature/change/x");
  assert.equal(suggestBranchName("claude"), "change/update");
  assert.equal(suggestBranchName("fix/already-clean"), "fix/already-clean");
});

test("detectBranch returns a structured finding with a remedy, or null when clean", () => {
  const f = detectBranch("copilot/thing");
  assert.equal(f.kind, "branch");
  assert.equal(f.remedy.action, "rename-branch");
  assert.equal(f.remedy.suggestion, "change/thing");
  assert.equal(detectBranch("feature/clean"), null);
});

test("detectCommits flags forbidden identity AND body trailers", () => {
  const log = [
    "Claude\tnoreply@anthropic.com\tHuman\thuman@example.com\tabc123",
    "Human\thuman@example.com\tHuman\thuman@example.com\tdef456",
  ].join("\n");
  const bodies = [
    { sha: "def456", body: `Add feature\n\n${COAUTHOR}: Claude <noreply@anthropic.com>` },
    { sha: "aaa111", body: "Clean commit message with no signature" },
  ];
  const findings = detectCommits(log, bodies);
  const kinds = findings.map((f) => f.kind).sort();
  assert.deepEqual(kinds, ["commit-body", "commit-identity"]);
});

test("detectCommits is clean on human commits with plain messages", () => {
  const log = "Human\thuman@example.com\tHuman\thuman@example.com\tabc123";
  const bodies = [{ sha: "abc123", body: "Fix the bug\n\nThis explains the change plainly." }];
  assert.deepEqual(detectCommits(log, bodies), []);
});

test("detectText finds AI signatures per line and points at the exact spot", () => {
  const text = ["Normal line", `See https://${SESSION_URL}/session_x`, "another normal line"].join("\n");
  const findings = detectText("pr_body", "PR#95", text);
  assert.equal(findings.length, 1);
  assert.equal(findings[0].where, "PR#95:2");
});

test("AI_SIGNATURE_RE matches the canonical set and is stateless across calls", () => {
  for (const s of [`${COAUTHOR}: X`, GEN_BY, AI_CLICHE, SESSION_URL]) {
    assert.equal(AI_SIGNATURE_RE.test(s), true, `should match: ${s}`);
    // No global flag: repeated .test on the same regex must be stateless.
    assert.equal(AI_SIGNATURE_RE.test(s), true, `stateless re-test: ${s}`);
  }
  assert.equal(AI_SIGNATURE_RE.test("a normal commit message"), false);
});

test("formatRemedy renders actionable git commands for a branch finding", () => {
  const out = formatRemedy([detectBranch("claude/fix")]);
  assert.match(out, /git branch -m change\/fix/);
  assert.match(out, /git push origin -u change\/fix/);
});

test("formatRemedy on no findings is a clean message", () => {
  assert.match(formatRemedy([]), /No AI-participation signatures found/);
});
