import { test } from "node:test";
import assert from "node:assert/strict";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { parsePrNumber, collectPrFindings } from "../scripts/hygiene.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

function cli(...args) {
  return spawnSync("node", [join(root, "scripts/hygiene.mjs"), ...args], { encoding: "utf8", timeout: 30000 });
}

// Assemble the banned session-URL literal from fragments so this test file stays
// clean under the house-style linter (same convention as detect-attribution tests).
const SESSION_URL = "claude" + ".ai/code";

test("parsePrNumber parses a positive integer and rejects junk", () => {
  assert.equal(parsePrNumber(["check"]), null);
  assert.equal(parsePrNumber(["--pr", "42"]), 42);
  assert.throws(() => parsePrNumber(["--pr", "abc"]), /positive integer/);
  assert.throws(() => parsePrNumber(["--pr", "-3"]), /positive integer/);
  assert.throws(() => parsePrNumber(["--pr"]), /positive integer/);
});

test("collectPrFindings flags a footer in the PR body via an injected client", async () => {
  const client = {
    fetchPr: async () => ({ title: "A clean title", body: `Real description.\n\n---\n_Generated by [Claude Code](https://${SESSION_URL}/session_abc)_` }),
    fetchIssueComments: async () => [],
  };
  const findings = await collectPrFindings(7, client);
  assert.equal(findings.length, 1);
  assert.equal(findings[0].kind, "pr_body");
  assert.match(findings[0].where, /PR#7 body/);
});

test("collectPrFindings flags a signature in a comment", async () => {
  const client = {
    fetchPr: async () => ({ title: "t", body: "clean body" }),
    fetchIssueComments: async () => [
      { id: 11, body: "looks good" },
      { id: 12, body: `see https://${SESSION_URL}/session_xyz for the run` },
    ],
  };
  const findings = await collectPrFindings(9, client);
  assert.equal(findings.length, 1);
  assert.equal(findings[0].kind, "pr_comment");
  assert.match(findings[0].where, /comment 12/);
});

test("collectPrFindings is clean on a PR with no signatures", async () => {
  const client = {
    fetchPr: async () => ({ title: "Add a feature", body: "This change adds X and verifies it with tests." }),
    fetchIssueComments: async () => [{ id: 1, body: "Nice work" }],
  };
  assert.deepEqual(await collectPrFindings(1, client), []);
});

test("CLI: --pr is rejected for fix (mutating a PR is out of scope)", () => {
  const r = cli("fix", "--pr", "5");
  assert.strictEqual(r.status, 2);
  assert.match(r.stderr, /does not support --pr/);
});

test("CLI: a malformed --pr value exits 2", () => {
  const r = cli("check", "--pr", "abc");
  assert.strictEqual(r.status, 2);
  assert.match(r.stderr, /positive integer/);
});

test("CLI: check and explain and fix still work locally (no --pr)", () => {
  // On this branch (a compliant name, clean commits) local hygiene passes.
  assert.strictEqual(cli("check").status, 0);
  assert.strictEqual(cli("explain").status, 0);
  assert.strictEqual(cli("fix").status, 0);
});
