import { test } from "node:test";
import assert from "node:assert/strict";
import {
  matchNearMissBranch,
  matchNearMissIdentity,
  matchNearMissText,
  formatStagedLine,
  normalizeForMatch,
  TIER1_TOKENS,
  TIER2_TOKENS,
} from "../scripts/lib/near-miss.mjs";
import { STAGED_LINE_RE } from "../scripts/lib/learnings.mjs";

// Assemble a strict AI-signature literal from fragments so this test file does not
// itself contain the exact phrase the house-style linter bans (same convention as
// tests/detect-attribution.test.mjs).
const COAUTHOR = "Co-" + "Authored-" + "By";

test("Tier-1 catches separator-and-spelling evasions of a strict token", () => {
  for (const name of ["feature/claude-code", "feature/claude_code", "wip/claudecode"]) {
    const f = matchNearMissBranch(name);
    assert.ok(f, `${name} should be a near-miss`);
    assert.equal(f.tier, 1);
    assert.equal(f.token, "claude");
  }
});

test("Tier-1 catches a new vendor token not yet in the strict denylist", () => {
  const f = matchNearMissBranch("wip/mistral-adapter");
  assert.equal(f.tier, 1);
  assert.equal(f.token, "mistral");
});

test("Tier-2 matches only an exact branch segment, not a substring", () => {
  assert.equal(matchNearMissBranch("grok/thing").token, "grok");
  assert.equal(matchNearMissBranch("assistant/foo").token, "assistant");
  // "grokking" and "assistants" are different words: exact-segment must not fire.
  assert.equal(matchNearMissBranch("feature/grokking-ui"), null);
  assert.equal(matchNearMissBranch("feature/assistants-list"), null);
});

test("the widener never duplicates a finding the strict gate already catches", () => {
  // Strict branchHasModelSegment / isForbiddenIdentity / AI_SIGNATURE_RE own these.
  assert.equal(matchNearMissBranch("claude/foo"), null);
  assert.equal(matchNearMissBranch("ai/telemetry"), null);
  assert.equal(matchNearMissIdentity("Claude", "noreply@anthropic.com"), null);
  assert.deepEqual(matchNearMissText("body", `${COAUTHOR}: Claude <x@anthropic.com>`), []);
});

test("identity near-miss catches a vendor name and a vendor email domain", () => {
  assert.equal(matchNearMissIdentity("Mistral Bot", "x@mistral.ai").token, "mistral");
  assert.equal(matchNearMissIdentity("grok", "x@example.com").token, "grok");
});

test("free-text scanning needs a vendor token AND an attribution cue", () => {
  // Vendor token in an attribution context fires (including separator-joined trailers).
  assert.equal(matchNearMissText("body", "Generated by Mistral large").length, 1);
  assert.equal(matchNearMissText("body", "Co_Authored_By: DeepSeek model").length, 1);
  // A vendor named without an attribution cue is ordinary prose: it must not fire.
  assert.deepEqual(matchNearMissText("body", "we evaluated mistral for the adapter"), []);
  assert.deepEqual(matchNearMissText("body", "vendors not yet denylisted like mistral"), []);
  // Ordinary prose containing a Tier-2 word or a legit vendor mention never fires
  // (the documented false-positive lessons), cue or not.
  assert.deepEqual(matchNearMissText("body", "She is an assistant professor"), []);
  assert.deepEqual(matchNearMissText("body", "Once you grok this pattern it is clear"), []);
  assert.deepEqual(matchNearMissText("body", "The argument does not cohere"), []);
  assert.deepEqual(matchNearMissText("body", "Update the Claude adapter config"), []);
  assert.deepEqual(matchNearMissText("body", "See CODEX.md for the Codex agent"), []);
});

test("normalizeForMatch strips separators and whitespace, lowercasing", () => {
  assert.equal(normalizeForMatch("Claude-Code"), "claudecode");
  assert.equal(normalizeForMatch("feature/GPT_4"), "featuregpt4");
});

test("Tier vocabularies are disjoint (a token has one precision tier)", () => {
  for (const t of TIER2_TOKENS) assert.ok(!TIER1_TOKENS.includes(t), `${t} in both tiers`);
});

test("formatStagedLine emits a line the learnings parser accepts", () => {
  const f = matchNearMissBranch("wip/mistral-adapter");
  const line = formatStagedLine(f, { date: "2026-07-02", evidence: "detect-near-miss run on wip/mistral-adapter" });
  assert.match(line, STAGED_LINE_RE, `formatStagedLine output is not a valid staged line: ${line}`);
});
