#!/usr/bin/env node
// House-style linter. Keeps shipped text plain and free of machine-prose tells
// and AI authorship signatures. Runs over Markdown and source text.
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, extname } from "node:path";

const ROOT = process.argv[2] || ".";
const TEXT_EXT = new Set([".md", ".mjs", ".js", ".ts", ".json", ".yaml", ".yml", ".astro", ".css", ".html", ".txt"]);
const SKIP_DIRS = new Set(["node_modules", ".git", "dist", ".astro", "build"]);
// The linter defines the banned patterns, so it must not scan itself.
const SKIP_FILES = new Set(["check-style.mjs"]);

const RULES = [
  { name: "em dash", re: /—/, hint: "Use a period, comma, colon, or parentheses." },
  { name: "phrase: not just", re: /\bnot just\b/i, hint: "State the point directly." },
  { name: "phrase: not only", re: /\bnot only\b/i, hint: "State the point directly." },
  { name: "phrase: it is not X it is Y", re: /\bit('?s| is) not\b[^.]*\bit('?s| is)\b/i, hint: "Say what it is." },
  { name: "AI signature", re: /\b(co-authored-by|generated by (claude|gpt|an ai)|as an ai language model)\b|\u{1F916}\s*generated with|claude\.ai\/code/iu, hint: "Remove AI authorship signatures." },
];

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    const s = statSync(full);
    if (s.isDirectory()) walk(full, out);
    else if (TEXT_EXT.has(extname(entry)) && !SKIP_FILES.has(entry)) out.push(full);
  }
  return out;
}

let problems = 0;
for (const file of walk(ROOT)) {
  const lines = readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    for (const rule of RULES) {
      if (rule.re.test(line)) {
        problems++;
        console.error(`${file}:${i + 1}: ${rule.name}. ${rule.hint}`);
      }
    }
  });
}

if (problems > 0) {
  console.error(`\nStyle check failed with ${problems} issue(s).`);
  process.exit(1);
}
console.log("Style check passed.");
