#!/usr/bin/env node
// Modonome snapshot command. Reads a repository and writes a tiered, Merkle-verified
// artifact under .modonome/snapshot/ that an LLM can load instead of re-reading the
// whole repo. Safe by default: it only writes under the snapshot directory and the
// root llms.txt, and needs no arming.
//
// Usage:
//   node scripts/snapshot.mjs [dir]                 write the snapshot artifact
//   node scripts/snapshot.mjs [dir] --check         fail or warn if the committed artifact is stale
//   node scripts/snapshot.mjs [dir] --verify        recompute hashes from disk and report drift
//   node scripts/snapshot.mjs [dir] --tier 0|1      print a tier to stdout
//   node scripts/snapshot.mjs [dir] --since <ref>   print the file-level delta since a git ref
//   node scripts/snapshot.mjs [dir] --pack          write a single portable .msnap bundle
//   node scripts/snapshot.mjs [dir] --parser <name> heuristic (default) or tree-sitter (optional)
//   node scripts/snapshot.mjs [dir] --strict-redact apply the full secret-pattern set
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { canonicalize } from "./lib/canonical-json.mjs";
import { parseFlatYaml } from "./lib/yaml-lite.mjs";
import { buildSnapshot } from "./lib/snapshot-core.mjs";
import { walkRepo, loadIgnore } from "./lib/snapshot-walk.mjs";
import { hashFileContent, buildMerkleTree } from "./lib/merkle.mjs";
import { loadCache, saveCache, changedPaths, gitHead } from "./lib/snapshot-cache.mjs";
import { registerAdapter } from "./lib/lang-adapters/index.mjs";
import { registerTreeSitter } from "./lib/lang-adapters/tree-sitter.mjs";

function flagValue(argv, name) {
  const i = argv.indexOf(name);
  return i !== -1 && i + 1 < argv.length ? argv[i + 1] : null;
}

function readConfig(root) {
  const p = join(root, ".modonome", "config.yaml");
  if (!existsSync(p)) return {};
  try { return parseFlatYaml(readFileSync(p, "utf8")); } catch { return {}; }
}

function snapshotDir(root) { return join(root, ".modonome", "snapshot"); }

function loadCommittedSignature(root) {
  const p = join(snapshotDir(root), "signature.json");
  if (!existsSync(p)) return null;
  try { return JSON.parse(readFileSync(p, "utf8")); } catch { return null; }
}

function llmsText(signature) {
  return [
    `# ${signature.generated_for}`,
    "",
    "> Machine-readable repository snapshot for LLM context, generated by Modonome.",
    "",
    "## Modonome snapshot",
    "- [Repo signature](.modonome/snapshot/signature.json): Tier 0 fingerprint. If merkle_root is unchanged, the repo is unchanged.",
    "- [Repo map, Markdown](.modonome/snapshot/map.md): Tier 1 modules, public API signatures, import edges, attention ranking.",
    "- [Repo map, JSON](.modonome/snapshot/map.json): the same map in machine-readable form.",
    "",
  ].join("\n");
}

function badgeJson(signature, map) {
  return {
    schemaVersion: 1,
    label: "snapshot",
    message: `${signature.size.files} files, ${map.token_estimate} tok`,
    color: "blue",
  };
}

function writeArtifact(root, built) {
  const dir = snapshotDir(root);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "signature.json"), canonicalize(built.signature) + "\n");
  writeFileSync(join(dir, "map.json"), canonicalize(built.map) + "\n");
  writeFileSync(join(dir, "map.md"), built.markdown + "\n");
  writeFileSync(join(dir, "badge.json"), canonicalize(badgeJson(built.signature, built.map)) + "\n");
  writeFileSync(join(root, "llms.txt"), llmsText(built.signature));
}

function buildOptions(root, argv, now) {
  const cfg = readConfig(root);
  const snap = cfg.snapshot || {};
  const strictRedact = argv.includes("--strict-redact") || snap.strict_redact === true;
  const tokenBudget = Number(flagValue(argv, "--budget")) || Number(snap.token_budget) || undefined;
  return {
    now,
    strictRedact,
    tokenBudget,
    prev: loadCommittedSignature(root),
    generatedFor: basename(root === "." ? process.cwd() : root) || "repo",
  };
}

function nowIso() { return new Date().toISOString(); }

// Resolve incremental build inputs. --full forces a from-scratch rebuild. Otherwise
// load the cache and ask git what changed; a missing cache or unusable git yields a
// full rebuild that produces identical output.
function incrementalInputs(root, argv) {
  if (argv.includes("--full")) return { cache: null, changed: null };
  const cache = loadCache(root);
  const changed = cache ? changedPaths(root, cache) : null;
  return { cache, changed };
}

// Recompute file hashes and the Merkle root directly from disk. Used by --verify.
function recomputeMerkle(root) {
  const files = walkRepo(root, { ignore: loadIgnore(root) });
  const entries = files.map((f) => ({ relPath: f.relPath, hash: hashFileContent(readFileSync(f.absPath)) }));
  return { files, ...buildMerkleTree(entries), fileHashes: Object.fromEntries(entries.map((e) => [e.relPath, e.hash])) };
}

// A --since ref is free-form git revision syntax (branch, tag, HEAD~N, a SHA), so
// it cannot be restricted to a fixed pattern the way a cache-internal SHA can. The
// one property that must hold is that it does not start with "-": a value like
// "--output=/path" would otherwise be parsed by git as an option, not a revision,
// and some git options can read or write files (argument injection).
function isSafeGitRevision(value) {
  return typeof value === "string" && value.length > 0 && !value.startsWith("-");
}

function gitDelta(root, ref) {
  if (!isSafeGitRevision(ref)) return { error: `refusing unsafe git ref: ${ref}`, added: [], removed: [], changed: [] };
  const r = spawnSync("git", ["diff", "--name-status", ref, "--"], { cwd: root, encoding: "utf8", timeout: 15000 });
  if (r.status !== 0) return { error: `git diff against ${ref} failed`, added: [], removed: [], changed: [] };
  const added = [], removed = [], changed = [];
  for (const line of r.stdout.split("\n")) {
    const parts = line.split("\t");
    if (parts.length < 2) continue;
    const code = parts[0][0];
    const path = parts[parts.length - 1];
    if (code === "A") added.push(path);
    else if (code === "D") removed.push(path);
    else changed.push(path);
  }
  added.sort(); removed.sort(); changed.sort();
  return { added, removed, changed };
}

// Flags that consume the following argument as a value, so it is not positional.
const VALUE_FLAGS = new Set(["--parser", "--since", "--tier", "--budget", "--pack-out", "--sign"]);

function positional(argv) {
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("-")) { if (VALUE_FLAGS.has(a)) i++; continue; }
    if (i > 0 && VALUE_FLAGS.has(argv[i - 1])) continue;
    return a;
  }
  return ".";
}

// Register the tree-sitter parser when requested via --parser or config, with a
// graceful fallback to the heuristic default when tree-sitter is not installed.
async function maybeRegisterParser(root, argv) {
  const cfg = readConfig(root);
  const parser = flagValue(argv, "--parser") || (cfg.snapshot && cfg.snapshot.parser) || "heuristic";
  if (parser !== "tree-sitter") return;
  const ok = await registerTreeSitter(registerAdapter);
  if (!ok) console.warn("[warn] tree-sitter not available; using the heuristic parser.");
}

async function main(argv) {
  const root = positional(argv);
  await maybeRegisterParser(root, argv);

  // --since: print the file-level delta since a git ref. Writes nothing.
  const since = flagValue(argv, "--since");
  if (since) {
    const delta = gitDelta(root, since);
    console.log(JSON.stringify({ from_ref: since, ...delta }, null, 2));
    process.exit(delta.error ? 1 : 0);
  }

  // --verify: recompute from disk and compare against the committed signature.
  if (argv.includes("--verify")) {
    const committed = loadCommittedSignature(root);
    if (!committed) { console.error("No committed snapshot to verify. Run: modonome snapshot"); process.exit(1); }
    const live = recomputeMerkle(root);
    if (live.root === committed.merkle_root) {
      console.log(`Snapshot verified. Merkle root matches: ${live.root}`);
      process.exit(0);
    }
    console.error(`Snapshot drift. Committed ${committed.merkle_root}, live ${live.root}.`);
    process.exit(1);
  }

  // --tier: print a committed tier, or build in memory when none is committed.
  const tier = flagValue(argv, "--tier");
  if (tier !== null) {
    const dir = snapshotDir(root);
    if (tier === "0") {
      const p = join(dir, "signature.json");
      console.log(existsSync(p) ? readFileSync(p, "utf8").trimEnd() : canonicalize(buildSnapshot(root, buildOptions(root, argv, "1970-01-01T00:00:00.000Z")).signature));
    } else {
      const p = join(dir, "map.json");
      console.log(existsSync(p) ? readFileSync(p, "utf8").trimEnd() : canonicalize(buildSnapshot(root, buildOptions(root, argv, "1970-01-01T00:00:00.000Z")).map));
    }
    process.exit(0);
  }

  // --check: rebuild deterministically and compare against committed artifact.
  if (argv.includes("--check")) {
    const committed = loadCommittedSignature(root);
    const cfg = readConfig(root);
    const mode = (cfg.snapshot && cfg.snapshot.ci_mode) || "warn";
    if (mode === "disabled") { console.log("Snapshot check disabled (snapshot.ci_mode: disabled)."); process.exit(0); }
    const fail = () => {
      const msg = "Snapshot is out of date. Run: node scripts/snapshot.mjs .";
      if (mode === "fail") { console.error(msg); process.exit(1); }
      console.warn(`[warn] ${msg}`);
      process.exit(0);
    };
    if (!committed) { console.error("No committed snapshot found."); fail(); return; }
    // Fast path: the map and signature are derived deterministically from file
    // content, so if the recomputed Merkle root matches, the snapshot is provably
    // current without the cost of a full rebuild (extraction, graph, render).
    const liveRoot = recomputeMerkle(root).root;
    if (liveRoot === committed.merkle_root) { console.log("Snapshot is current."); process.exit(0); }
    const built = buildSnapshot(root, buildOptions(root, argv, committed.generated_at));
    const dir = snapshotDir(root);
    const sameSig = canonicalize(built.signature) === canonicalize(committed);
    const sameMap = existsSync(join(dir, "map.json")) && canonicalize(built.map) === canonicalize(JSON.parse(readFileSync(join(dir, "map.json"), "utf8")));
    const sameMd = existsSync(join(dir, "map.md")) && built.markdown + "\n" === readFileSync(join(dir, "map.md"), "utf8");
    if (sameSig && sameMap && sameMd) { console.log("Snapshot is current."); process.exit(0); }
    fail();
    return;
  }

  // --pack: write a single portable bundle.
  if (argv.includes("--pack")) {
    const { cache, changed } = incrementalInputs(root, argv);
    const built = buildSnapshot(root, { ...buildOptions(root, argv, nowIso()), cache, changed });
    const dir = snapshotDir(root);
    mkdirSync(dir, { recursive: true });
    saveCache(root, { built_at_head: gitHead(root), entries: built.cacheEntries });
    const packPath = flagValue(argv, "--pack-out") || join(dir, "snapshot.msnap");
    writeFileSync(packPath, built.packBytes);
    console.log(`Wrote ${packPath} (${built.signature.size.files} files, ${built.map.token_estimate} map tokens).`);
    process.exit(0);
  }

  if (argv.includes("--sign")) {
    console.warn("[warn] Signed snapshots ship in a later phase. Writing an unsigned snapshot.");
  }

  // Default: write the artifact (incremental when a cache and git are available).
  const { cache, changed } = incrementalInputs(root, argv);
  const built = buildSnapshot(root, { ...buildOptions(root, argv, nowIso()), cache, changed });
  writeArtifact(root, built);
  saveCache(root, { built_at_head: gitHead(root), entries: built.cacheEntries });
  const dir = snapshotDir(root);
  console.log(`Wrote snapshot to ${dir}`);
  console.log(`  files: ${built.signature.size.files}  merkle: ${built.signature.merkle_root}`);
  console.log(`  map tokens: ${built.map.token_estimate}/${built.map.token_budget}${built.map.truncated ? " (truncated)" : ""}  api: ${built.map.api.length}  modules: ${built.map.modules.length}`);
  console.log(`  build: ${built.stats.rebuilt} rebuilt, ${built.stats.reused} reused from cache`);
  if (built.cycle && built.cycle.cyclic) console.log(`  note: import cycle detected: ${built.cycle.cycle.join(" -> ")}`);
  process.exit(0);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}

export { llmsText, badgeJson, gitDelta };
