#!/usr/bin/env node
// Generate the package barrel and the aggregated component stylesheet by scanning
// src/components/*/. Each component lives in its own directory and is fully
// self-contained, so this codegen is what lets many authors add components in
// parallel without ever editing a shared file. Run before every build.
import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const componentsDir = join(here, "src/components");

const dirs = existsSync(componentsDir)
  ? readdirSync(componentsDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort()
  : [];

const withIndex = dirs.filter((d) => existsSync(join(componentsDir, d, "index.ts")));
const withCss = dirs.filter((d) => existsSync(join(componentsDir, d, `${d}.css`)));

// Barrel: re-export every component directory.
const barrel =
  "// Generated by gen-barrel.mjs. Do not edit by hand; add a component directory\n" +
  "// under src/components/ and rebuild.\n" +
  'export * from "./lib/cx";\n' +
  'export * from "./lib/format";\n' +
  'export * from "./tokens/tokens";\n' +
  withIndex.map((d) => `export * from "./components/${d}/index";`).join("\n") +
  "\n";
writeFileSync(join(here, "src/index.ts"), barrel);

// Aggregated component CSS, imported by src/styles.css.
const css =
  "/* Generated by gen-barrel.mjs. Do not edit; per-component styles live in\n" +
  "   src/components/<Name>/<Name>.css. */\n" +
  withCss.map((d) => `@import "./components/${d}/${d}.css";`).join("\n") +
  "\n";
writeFileSync(join(here, "src/components.gen.css"), css);

console.log(`gen-barrel: ${withIndex.length} components exported, ${withCss.length} stylesheets.`);
